# Generated by Django 4.1.3 on 2023-02-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgroundData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('commodity_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='jd_data',
            name='add_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jd_data',
            name='d_price',
            field=models.FloatField(),
        ),
    ]
